apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 80
      targetPort: 3006
      name: http
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: server
        image: frontend
        ports:
        - containerPort: 3006
          name: http
        env:
        - name: NODE_ENV
          value: development
        - name: REACT_APP_USERS_SERVICE_URL
          value: http://localhost:3000
        - name: REACT_APP_MOVIES_SERVICE_URL
          value: http://localhost:3001
        - name: REACT_APP_RATINGS_SERVICE_URL
          value: http://localhost:3002
