apiVersion: v1
kind: Service
metadata:
  name: movies
  labels:
    app: movies
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: movies
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
  labels:
    app: movies
spec:
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - name: server
        image: movies
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: DATABASE_URL
          value: postgres://postgres:postgres@movies-db:5432/movies_dev
        - name: NODE_ENV
          value: development
        - name: TOKEN_SECRET
          value: changeme
